- instrument: DP1
  channel: 1
  min_current: 0.1
  max_current: 0.3
- instrument: DP1
  channel: 2
  min_current: 0.1
  max_current: 0.3
- instrument: DP1
  channel: 3
  min_current: 0.3
  max_current: 0.5
